services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    env_file:
      - ${ENV_FILE}
    ports:
      - '3307:3306'
  bookswap:
    container_name: bookswapcontainer
    build:
      context: .
      args:
        CONTAINER_PORT: ${CONTAINER_PORT}
    image: bookswap:v1
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    expose:
      - ${CONTAINER_PORT}
    ports:
      - ${CONTAINER_PORT}:${HOST_PORT}
