# Database
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: bookswap
MYSQL_USERNAME: root
MYSQL_PASSWORD: p00rGe()n

# Server
CONTAINER_PORT: 8080
ACTIVE_PROFILE: dev

# Mail
MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: jojekgobbany@gmail.com
MAIL_PASSWORD: ztvk fows vxqz tqnw

# UI
UI_APP_URL: http://localhost:4200/

# JWT
JWT_SECRET: 1d590942b3b007c79ac697a1a727aa0196239ab6ee12cb20fefb91db19113951
JWT_EXPIRATION_TIME: 86400000

# API
API_LOCATION_KEY: